# Generated by Django 3.2.7 on 2021-09-06 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Oops_modelans',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('answer1', models.TextField()),
                ('answer2', models.TextField()),
                ('answer3', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Oops_userans',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mailid', models.TextField(default='xyz')),
                ('answer', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=120)),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('number', models.IntegerField(primary_key=True, serialize=False)),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('mailid', models.TextField(primary_key=True, serialize=False)),
                ('password', models.TextField()),
                ('oops_score', models.TextField()),
                ('dbms_score', models.TextField()),
                ('os_score', models.TextField()),
            ],
        ),
    ]
