# Generated by Django 3.2.7 on 2021-09-06 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demo', '0002_dbms_modelans_dbms_question_dbms_userans'),
    ]

    operations = [
        migrations.CreateModel(
            name='Os_modelans',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('answer1', models.TextField()),
                ('answer2', models.TextField()),
                ('answer3', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Os_Question',
            fields=[
                ('number', models.IntegerField(primary_key=True, serialize=False)),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Os_userans',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mailid', models.TextField(default='xyz')),
                ('answer', models.TextField()),
            ],
        ),
    ]
