# Generated by Django 3.2.7 on 2021-09-07 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demo', '0003_os_modelans_os_question_os_userans'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='taken_test',
            field=models.BooleanField(default=False),
        ),
    ]
