# Generated by Django 3.2.7 on 2021-09-07 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demo', '0005_oops_userans_num'),
    ]

    operations = [
        migrations.AddField(
            model_name='dbms_userans',
            name='num',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='os_userans',
            name='num',
            field=models.IntegerField(default=1),
        ),
    ]
